name: connector_api
description: Dart bindings for connector protobuffers
version: 0.0.2
author: raf924

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  protobuf: ^2.0.0
  grpc: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec